jdk: oraclejdk8
language: java
script: mvn clean install sonar:sonar -Dsonar.analysis.mode=preview -Dsonar.github.pullRequest=$PULL_REQUEST_ID -Dsonar.github.oauth=$GITHUB_ACCESS_TOKEN -Dsonar.host.url=https://server/sonarqube -Dsonar.login=$SONARQUBE_ACCESS_TOKEN