language: node_js
addons:
  sonarqube: true

script:
  # other script steps might be done before running the actual SonarQube analysis
  - sonar-scanner 
    -Dsonar.sources=.
    -Dsonar.analysis.mode=preview
    -Dsonar.projectKey=sandeep-digital-sonar-test1
    -Dsonar.projectName=sandeep-digital-sonar-test1
    -Dsonar.host.url=$SONAR_SERVER
    -Dsonar.github.oauth=$GITHUB_ACCESS_TOKEN
    -Dsonar.github.repository=xenotime-india/sonar-qube-test
    -Dsonar.login=$SONARQUBE_ACCESS_TOKEN
    -Dsonar.github.pullRequest=$TRAVIS_PULL_REQUEST